#!/usr/bin/env node
/**
 * Copies dependency-free TypeScript from packages/shared into the Supabase
 * functions directory, so Deno can import it without reaching outside the
 * folder that `supabase functions deploy` uploads.
 *
 *   pnpm sync:shared          copy
 *   pnpm sync:shared:check    exit 1 if the copy is stale (used by CI)
 *
 * The destination is gitignored. Never edit files under _shared/gen.
 */
import { mkdir, readdir, readFile, rm, stat, writeFile } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(ROOT, 'packages/shared/src')
const DEST = join(ROOT, 'supabase/functions/_shared/gen')
const SUBDIRS = ['schemas', 'domain', 'types']
const BANNER = '// GENERATED by `pnpm sync:shared` — do not edit. Source: packages/shared/src/\n'

const checkOnly = process.argv.includes('--check')

async function collect(dir, base = dir, out = []) {
  let entries
  try {
    entries = await readdir(dir, { withFileTypes: true })
  } catch (err) {
    if (err.code === 'ENOENT') return out
    throw err
  }
  for (const entry of entries) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) await collect(full, base, out)
    else if (entry.name.endsWith('.ts') && !entry.name.endsWith('.test.ts')) {
      out.push(relative(base, full))
    }
  }
  return out
}

async function main() {
  if (!(await stat(SRC).catch(() => null))) {
    console.error(`sync:shared — source not found: ${SRC}`)
    process.exit(1)
  }

  const files = []
  for (const sub of SUBDIRS) {
    for (const rel of await collect(join(SRC, sub))) files.push(join(sub, rel))
  }

  if (files.length === 0) {
    console.log('sync:shared — nothing to copy yet')
    return
  }

  let stale = []
  for (const rel of files) {
    const content = BANNER + (await readFile(join(SRC, rel), 'utf8'))
    const target = join(DEST, rel)
    const existing = await readFile(target, 'utf8').catch(() => null)
    if (existing === content) continue
    stale.push(rel)
    if (!checkOnly) {
      await mkdir(dirname(target), { recursive: true })
      await writeFile(target, content, 'utf8')
    }
  }

  // Remove copies whose source no longer exists.
  const expected = new Set(files)
  for (const rel of await collect(DEST)) {
    if (expected.has(rel)) continue
    stale.push(`${rel} (orphaned)`)
    if (!checkOnly) await rm(join(DEST, rel))
  }

  if (checkOnly && stale.length > 0) {
    console.error('sync:shared — generated copies are stale:')
    for (const rel of stale) console.error(`  ${rel}`)
    console.error('\nRun `pnpm sync:shared` and commit nothing (the dir is gitignored).')
    process.exit(1)
  }

  console.log(
    checkOnly
      ? `sync:shared — up to date (${files.length} files)`
      : `sync:shared — copied ${files.length} files, ${stale.length} changed`,
  )
}

await main()
