-- Milestone 4 — the private channel to the moderator.
--
-- THIS TABLE HAS NO CLIENT POLICY AT ALL. Not for the subject, and — this is
-- the part that looks like an oversight and is not — NOT FOR THE REPORTER
-- EITHER. RLS is enabled with zero policies, which denies everything to
-- `authenticated` by construction, and the grants below withhold the privilege
-- as well. Two independent locks, because this is the one table where a leak
-- puts somebody at risk rather than merely embarrassing them.
--
-- The reporter learns their report landed from a notification, not from
-- reading the row back. The subject learns nothing, ever.

create type public.report_status as enum ('open', 'reviewing', 'actioned', 'dismissed');

create table public.reports (
  id             uuid primary key default gen_random_uuid(),
  -- Nullable and ON DELETE SET NULL: a departing bad actor must not be able to
  -- erase the safety record they generated by deleting their account.
  reporter_id    uuid references public.profiles(id) on delete set null,
  subject_id     uuid references public.profiles(id) on delete set null,
  category       text not null,
  body           text not null,
  related_type   text,
  related_id     uuid,
  status         public.report_status not null default 'open',
  moderator_note text,
  created_at     timestamptz not null default now(),
  resolved_at    timestamptz,

  constraint report_body_length check (char_length(body) between 1 and 2000),
  constraint report_category_known check (category in (
    'safety', 'harassment', 'no_show', 'misrepresentation', 'spam', 'other'
  )),
  constraint report_related_type_known check (
    related_type is null or related_type in ('stay', 'request', 'offer')
  ),
  constraint no_self_report check (
    reporter_id is null or subject_id is null or reporter_id <> subject_id
  )
);

create index reports_open on public.reports (created_at) where status = 'open';
create index reports_subject on public.reports (subject_id);
create index reports_reporter on public.reports (reporter_id);

comment on table public.reports is
  'Private moderator channel. No client may read this table — not even the '
  'person who filed the row. Written only by submit-report as service_role.';

-- ───────────────────────────────────────────────────────────────────────────
-- RLS: enabled, with deliberately no policies
--
-- An RLS-enabled table with no policy denies every row to every non-privileged
-- role. service_role bypasses RLS entirely, which is how submit-report writes.
-- ───────────────────────────────────────────────────────────────────────────
alter table public.reports enable row level security;

-- Belt and braces. Milestone 1's service_role migration grants ALL on ALL
-- tables in this schema to service_role, and ALTER DEFAULT PRIVILEGES extends
-- that to new tables — but nothing there grants `authenticated` anything, and
-- nothing should. Revoking explicitly makes that intent impossible to undo by
-- accident later.
revoke all on public.reports from anon, authenticated;

-- ───────────────────────────────────────────────────────────────────────────
-- Rate limit
--
-- Five in a rolling day. High enough that nobody with a real safety concern is
-- ever turned away, low enough that the moderator queue cannot be flooded.
-- ───────────────────────────────────────────────────────────────────────────
create or replace function public.recent_report_count(p_reporter uuid)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select count(*)::integer
  from public.reports
  where reporter_id = p_reporter
    and created_at > now() - interval '24 hours';
$$;

revoke all on function public.recent_report_count(uuid) from public, anon, authenticated;

-- ───────────────────────────────────────────────────────────────────────────
-- submit_report
--
-- One transaction: the report, the optional block, and the reporter's
-- confirmation. The moderator EMAIL is sent by the Edge Function rather than
-- from here, because it must not sit behind the notification sweep — safety
-- cannot wait for a cron tick.
-- ───────────────────────────────────────────────────────────────────────────
create or replace function public.submit_report(
  p_reporter     uuid,
  p_subject      uuid,
  p_category     text,
  p_body         text,
  p_related_type text default null,
  p_related_id   uuid default null,
  p_also_block   boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  if not exists (
    select 1 from public.profiles p
    where p.id = p_subject and p.status <> 'deleted'
  ) or p_subject = p_reporter then
    return jsonb_build_object('ok', false, 'error', 'subject_not_found');
  end if;

  if p_category not in ('safety', 'harassment', 'no_show', 'misrepresentation', 'spam', 'other') then
    return jsonb_build_object('ok', false, 'error', 'invalid_category');
  end if;

  if public.recent_report_count(p_reporter) >= 5 then
    return jsonb_build_object('ok', false, 'error', 'rate_limited');
  end if;

  insert into public.reports
    (reporter_id, subject_id, category, body, related_type, related_id)
  values
    (p_reporter, p_subject, p_category, p_body, p_related_type, p_related_id)
  returning id into v_id;

  -- Offered, never forced. Someone reporting a safety concern usually wants
  -- the person gone from their app immediately; someone reporting a no-show
  -- often does not.
  if p_also_block then
    insert into public.blocks (blocker_id, blocked_id)
    values (p_reporter, p_subject)
    on conflict do nothing;
  end if;

  -- The reporter's receipt. Carries no report content — this notification
  -- travels through Apple and Google like every other.
  --
  -- Enqueued WITHOUT a counterparty id in the payload, deliberately: the block
  -- above would otherwise suppress the reporter's own confirmation, and they
  -- would be left wondering whether the report went through.
  perform public.enqueue_notification(
    p_reporter,
    'report_received',
    jsonb_build_object('reportId', v_id)
  );

  return jsonb_build_object('ok', true, 'reportId', v_id);
end;
$$;

revoke all on function public.submit_report(uuid, uuid, text, text, text, uuid, boolean)
  from public, anon, authenticated;

comment on function public.submit_report is
  'Called only by the submit-report Edge Function as service_role. Returns the '
  'report id so the function can email the moderator; the response to the '
  'CLIENT never echoes report content, and there is no read path at all.';
